name: gerafrequencia
description: Gerador de frequências a partir de um arquivo YAML.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  pdf: ^3.10.8
  args: ^2.4.2
  http: ^1.2.1
  path: ^1.9.0
  yaml: ^3.1.2
  intl: ^0.18.1
  dartx: ^1.2.0
  dotenv: ^4.2.0
  dorm_framework: ^1.0.0-alpha.5
  dorm_annotations: ^1.0.0-alpha.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  dorm_generator:
    git:
      url: https://github.com/beet-software/dorm.git
      path: dorm_generator
      ref: develop

executables:
  gerafrequencia: generate